import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { App, Layout } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Content } from "antd/es/layout/layout";
import "@ant-design/v5-patch-for-react-19";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <App>
          <AntdRegistry>
            <Layout
              className="!overflow-hidden"
              style={{
                overflow: "hidden",
                width: "calc(100% - 8px)",
                maxWidth: "calc(100% - 8px)",
                minHeight: "100vh",
              }}
            >
              <Layout>
                <Content className="p-4">
                  {
                    <Suspense
                      fallback={
                        <div className="font-bold bg-green-950">Loading...</div>
                      }
                    >
                      {children}
                    </Suspense>
                  }
                </Content>
              </Layout>
            </Layout>
          </AntdRegistry>
        </App>
      </body>
    </html>
  );
}
